services:
  evcsmbackend:
    image: evcsmbackend-evcsmbackend:latest
    ports:
      - "5274:5274" 
      - "8080:80"
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mosquitto
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001" #for mqttwebsockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  mongo-data: